vars:
  address-groups:
    HOME_NET: "[10.10.10.0/24,10.10.20.0/24,10.10.30.0/24,10.10.40.0/24,10.10.50.0/24]"
    EXTERNAL_NET: "!$HOME_NET"

default-log-dir: /var/log/suricata

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert
        - dns
        - http
        - tls

runmode: workers

classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config

